let a=10;

try {
    let c=a/b;
} catch (error) {
    console.log("error catched");
}